### ISSUE TITLE
Portfolio deployment

### ISSUE THREAD

**Issue by Yacoubou-seidou** [Yacoubou-seidou/Portfolio#8]
Here is the link to my Portfolio page: https://yacoubou-seidou.github.io/Portfolio/

**Comment by wayungi** [comment]
- [ optional] Good work. You should submit this in a PR with changes to your  README.

**Comment by Yacoubou-seidou** [comment]
@wayungi  can you please help me?
Because I have already made the deployment since the start of this project.


![Capture d’écran 2023-02-27 085146](https://user-images.githubusercontent.com/84572891/221505146-c98015c1-635f-46b8-ad94-6893c918f886.png)
